### PR TITLE
Added description and screenshot files

### PR DESCRIPTION
**Pull request by ExcaliburZero**
Added a description and screenshot file that will be used by the Mod tab of the main menu of Minetest.

### CODE REVIEW

**Comment by HybridDog** [comment]
l guess you can use a jpg screenshot and name it "screenshot.png" to reduce the file size.

**Comment by ExcaliburZero** [comment]
@HybridDog I have done a test to see what the file size reduction would be through converting to a jpg and then a png using GIMP, then compressing the png. However, for some reason that made the file size bigger (253.4 KB to 842.8 KB).

I did another test whereby I changed the png image to use an 8 bit color pallet. That reduced the file size quite a bit (253.4 KB to 97.2 KB). It did result in a slight loss in quality, but not a very noticeable loss:
***Before:***
screenshot

***After:***
screenshot 3

**Comment by HybridDog** [comment]
@ExcaliburZero l don't mean converting it to jpg and then to png, l mean converting it to jpg and then naming it png:

before:
253.4kB


after:
100.4kB
screenshot

**Comment by ExcaliburZero** [comment]
@HybridDog That could work, but in at least the example you showed that method resulted in a lower quality and slightly higher file size than saving it as a PNG-8. So it might be better to go with a PNG-8 rather than a JPG renamed to a PNG.

Also, what did program and settings did you use to make the JPG? I tried saving it a a JPG in GIMP using a quality setting of 90 and got a file size of 231.5 kB.

**Comment by HybridDog** [comment]
75, float comma numbers, progressive, optimized

ln your PNG-8 file some colours are missing

**Comment by ExcaliburZero** [comment]
Yep, the PNG-8 removes a couple of colors to reduce the file size. While the JPG lowers the quality to reduce the file size.

Either method should be fine, as the mod tab of the main menu of Minetest, where the screenshot is primarily used, resizes the image down quite a bit. So the visual changes aren't all that noticeable.

**Comment by HybridDog** [comment]
here's a 92 kB screenshot:
screenshot

**Comment by ExcaliburZero** [comment]
@HybridDog That doesn't look all that bad. Though it does seem to lose quite a few colors on the water. I think I'll do a test to compare how it looks in the mod tab.

Also, I took a look at the dimensions of the resized image that is displayed in the mods tab, and it seems to display at a ratio of 3:2. So it may appear better on the screen if it uses that dimension ratio.

**Comment by ExcaliburZero** [comment]
@HybridDog Here is a comparison of the current screenshot image and the one you just posted.

***Current:***
screenshot from 2015-05-03 11 32 41

***New:***
screenshot from 2015-05-03 11 36 43

**Comment by sofar** [comment]
It appears the mod manager forces the aspec ratio, so the screen looks squished to me.

**Comment by sofar** [comment]
I recreated the screenshot.png from the original full size screenshot and sized it down to 600x400, as it seems that the in-game display has a 3:2 aspect ration. This brings the size of the screenshot down to 224k.

Note that the screenshot doesn't get sent to clients, so there's little reason to compress it further.

**Comment by ExcaliburZero** [comment]
@sofar The resized version you created looks a good bit better. You're right, the file size of the screenshot probably won't matter all that much.

**Comment by HybridDog** [comment]
To view the screenshot you need to download it, don't you?

**Comment by sofar** [comment]
On 05/04/2015 08:19 AM, HybridDog wrote:
> To view the screenshot you need to download it, don't you?

If you connect to a server where the mod is installed, you cannot see 
the mod manager, and so no client downloads this file.

If you download the mod yourself, then the size of the screenshot is not 
large at all. Not anywhere near an issue for github.com where the files 
are hosted. I could care less about 100k file difference for something 
that is not sent to every connecting client.

The total download of crops is a 260k zipfile. Things like Plantlife are 
4-5MB. Not worth this discussion even :^)

**Pull request merged**
